server:
  port: 80

spring:
  application:
    name: consumer-feign-hystrix-order

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/